// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://burcnavttzowimifhmsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cmNuYXZ0dHpvd2ltaWZobXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDMzNDAsImV4cCI6MjA2OTQ3OTM0MH0.JaCN5EPrHBNe1J6omQdbOGIq-XJRVvctD4CU_344634";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});